Issue 20
dotkernel/dot-log pull request #22
Opened 2023-07-18 08:41 UTC by cPintiuta

2023-07-18 11:26 UTC, alexmerlin requested changes
Please fix the following:
1. remove file header docblocks from all PHP files.
2. correct namespaces in all test files.

2023-07-18 11:26 UTC, alexmerlin commented on .gitignore
Please add empty line at the end of the file.

2023-07-18 11:26 UTC, alexmerlin commented on README.md
Please leave only one empty line between lines **6** and **11**.
In preparation for a `3.4.0` release, on the line with `PHP from Packagist` please replace the string `3.2.0` with `3.4.0`.

2023-07-18 11:26 UTC, alexmerlin commented on phpunit.xml
Please add empty line at the end of the file.

2023-07-18 11:26 UTC, alexmerlin commented on src/ConfigProvider.php
Please remove PHPDoc comments from the methods.

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
>      /**
Please:
* remove PHPDoc comment
* add return type hint to the method
* use the correct ContainerInterface reference

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
> +    public function __invoke(containerinterface $container, $requestedName, ?array $options = null)
Please:
* remove `@param` and `@return` references from and add necessary `@throws` to the PHPDoc comment
* add return type hint to the method
* use the correct ContainerInterface reference

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
> +use interop\container\containerinterface;
Please undo this change.

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
> +    public function getConfig(containerinterface $services): array
Wasn't there any complain from the code quality tools when you changed this from `protected` to `public`?

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
>      /**
Please remove PHPDoc comment.

2023-07-18 11:26 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
>      /**
Please remove PHPDoc comment and add missing `@throws` tags.

2023-07-18 17:52 UTC, cPintiuta commented on src/Factory/LoggerAbstractServiceFactory.php
>      /**
return type hint for "subConfigKey"  cannot be assigned as will not match base class (paresnt)

2023-07-18 17:52 UTC, cPintiuta commented on src/Factory/LoggerAbstractServiceFactory.php
> +    public function __invoke(containerinterface $container, $requestedName, ?array $options = null)
return type cannot be assigned to "requestedName" as will not match parent

2023-07-18 17:53 UTC, cPintiuta commented on src/Factory/LoggerAbstractServiceFactory.php
> +    public function getConfig(containerinterface $services): array
IAt first i  had a test for this but is not relevant anymore so it will be back to protected

2023-07-18 17:55 UTC, cPintiuta commented
in some places i let the docblock for params because type hint cannot be assigned as will not match the parent

2023-07-19 04:34 UTC, alexmerlin commented on src/Factory/LoggerAbstractServiceFactory.php
>      /**
The only thing left here is to use the correct ContainerInterface (with CamelCase instead of lowercase):
`use Interop\Container\ContainerInterface;`
Also, there are 4 methods that receive this argument - please don't forget to modify those as well.

2023-07-19 04:50 UTC, alexmerlin requested changes
Two items left to fix:
* fix `ContainerInterface` usage in `src/Factory/LoggerAbstractServiceFactory.php` as I suggested in [this comment](https://github.com/dotkernel/dot-log/pull/22#discussion_r1267524750)
* please add an empty line at the end of `OSSMETADATA` file.

2023-07-19 08:39 UTC, alexmerlin approved these changes

2023-07-19 09:05 UTC, merged